name: Android build

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build_and_publish:
    env:
      KEYSTORE_JKS: ${{ secrets.ANDROID_KEYSTORE_FILE }}
      GOOGLE_PLAY_JSON: ${{ secrets.GOOGLEPLAY_SERVICE_ACCOUNT_FILE }}
      FIREBASE_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FILE }}

    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create Firebase JSON
          - echo $FIREBASE_JSON | base64 -d > app/service-account-firebase-dist.json

      - name: Create Google Play JSON
          - echo $GOOGLE_PLAY_JSON | base64 -d > app/service-account.json

      - name: Create JKS
          - echo $KEYSTORE_JKS | base64 -d > app/teste.jks

      - name: Build Project
        run: ./gradlew assemble