name: Publish App

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish App
        run: ./gradlew assembleRelease publishBundle --track production