name: Publish App

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create Firebase JSON
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FILE }}" | base64 -d > app/service-account-firebase-dist.json

      - name: Create Google Play JSON
        run: echo "${{ secrets.GOOGLEPLAY_SERVICE_ACCOUNT_FILE }}"| base64 -d > app/service-account.json

      - name: Create JKS
        run: echo "${{ secrets.ANDROID_KEYSTORE_FILE }}" | base64 -d > app/teste.jks

      - name: Build Project
        run: ./gradlew assemble
